import './plugins/app/jquery.min.js';
import './plugins/app/bootstrap.bundle.min.js';
import './plugins/app/jquery.hoverIntent.min.js';
import './plugins/app/jquery.waypoints.min.js';
import './plugins/app/superfish.min.js';
import './plugins/app/owl.carousel.min.js';
import './template/app/wNumb.js';
// import './plugins/bootstrap-input-spinner.js';
import './plugins/app/jquery.magnific-popup.min.js';
import './plugins/app/nouislider.min.js';
import './template/app/main.js';
import './template/app/cart.js';
import './template/app/wishlist.js';
